train_image_task:
    description: > 
      Estude e compreenda o dataset de imagens que você recebeu 
      Treine o modelo yolov8n.pt com os seguintes parametros
       - name: treino de postes 
      -  epochs: 30 
    expected_output: > 
      Diga o que você percebeu durante o treinamento de imagens
    agent: train_analyst

image_analysis_task:
    description: > 
      Com base no conhecimento do agete train_analyst fale sobre o ponto de vista dele
    expected_output: > 
      Analise a imagem e faça um texto sobre fibra optica, se a imagem for da categoria has fiber optic. 
      Caso a imagem seja da categoria there is no fiber optics', fale sobre a categoria de postes 
      Escreva o texto no formato de markdown com '```'
    agent: image_analyst